from fastapi import FastAPI,Depends,status,Response,HTTPException
from . import models


# from passlib.context import CryptContext
from .database import engine,get_db
from .routers import tech,user
app=FastAPI()

# used to create tables in my database
models.Base.metadata.create_all(engine)
app.include_router(tech.router)
app.include_router(user.router)
#autogenerated status code
# @app.post('/tech',status_code=status.HTTP_201_CREATED,tags=['techs'])
# def create(request:schemas.Tech,db:Session=Depends(get_db)):
#     new_tech=models.Tech(title=request.title,body=request.body,user_id=1)
#     db.add(new_tech)
#     db.commit()
#     db.refresh(new_tech)
#     return new_tech
# @app.delete('/tech/{id}',status_code=status.HTTP_204_NO_CONTENT,tags=['techs'])
# def destroy(id,db:Session=Depends(get_db)):
#     techs=db.query(models.Tech).filter(models.Tech.id==id)
#     if not techs.first():
#         raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,detail=f"Tech with id {id} is not available")
#     techs.delete(synchronize_session=False)
#     db.commit()
#     return 'done'
# @app.put('/tech/{id}',status_code=status.HTTP_202_ACCEPTED,tags=['techs'])
# def update(id,request:schemas.Tech,db:Session=Depends(get_db)):
#     techs=db.query(models.Tech).filter(models.Tech.id==id)
#     if not techs.first():
#         raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,detail=f"Tech with id {id} is not available")
#     techs.update(request.dict())
#     db.commit()
#     return 'updated'
# @app.get('/tech',response_model=List[schemas.ShowTech],tags=['techs'])  #here we have used list because we need a response that contains all the data of tech.
# def all(db:Session=Depends(get_db)):
#     techs=db.query(models.Tech).all()
#     return techs
# @app.get('/tech/{id}',status_code=200,response_model=schemas.ShowTech,tags=['techs'])
# def show(id,response:Response,db:Session=Depends(get_db)):
#     techs=db.query(models.Tech).filter(models.Tech.id==id).first()
#     if not techs:
#         raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,detail=f"Tech with id {id} is not available")
#         # response.status_code=status.HTTP_404_NOT_FOUND
#         # return {'detail':f"Tech with id {id} is not available"}
#     return techs
#hash the password
# pwd_cxt = CryptContext(schemes=["bcrypt"], deprecated="auto") this is hashing in same file another one is to create a class and then perform the hashing

#Create a user
# @app.post('/user',response_model=schemas.ShowUser,tags=['users'])
# def create_user(request:schemas.User,db:Session=Depends(get_db)):
#     # hashedPassword=pwd_cxt.hash(request.password)
#     new_user=models.User(name=request.name,email=request.email,password=Hash.bcrypt(request.password))
#     db.add(new_user)
#     db.commit()
#     db.refresh(new_user)
#     return new_user

# @app.get('/user/{id}',response_model=schemas.ShowUser,tags=['users'])
# def get_user(id:int,db:Session=Depends(get_db)):
#     user=db.query(models.User).filter(models.User.id==id).first()
#     if not user:
#         raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,detail=f"User with id {id} is not available")
#     return user
    


    #to define a routes or the endpoints in proper way in the swagger we use docs tags
